//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

using FANNCSharp;
namespace FannWrapperFloat {

internal class fann_connection : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal fann_connection(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(fann_connection obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~fann_connection() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          fannfloatPINVOKE.delete_fann_connection(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public uint FromNeuron {
    set {
      fannfloatPINVOKE.fann_connection_FromNeuron_set(swigCPtr, value);
    } 
    get {
      uint ret = fannfloatPINVOKE.fann_connection_FromNeuron_get(swigCPtr);
      return ret;
    } 
  }

  public uint ToNeuron {
    set {
      fannfloatPINVOKE.fann_connection_ToNeuron_set(swigCPtr, value);
    } 
    get {
      uint ret = fannfloatPINVOKE.fann_connection_ToNeuron_get(swigCPtr);
      return ret;
    } 
  }

  public float Weight {
    set {
      fannfloatPINVOKE.fann_connection_Weight_set(swigCPtr, value);
    } 
    get {
      float ret = fannfloatPINVOKE.fann_connection_Weight_get(swigCPtr);
      return ret;
    } 
  }

  public fann_connection() : this(fannfloatPINVOKE.new_fann_connection(), true) {
  }

}

}
