//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

using FannWrapperFloat;
namespace FannWrapper {

public class activationFunctionArray : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal activationFunctionArray(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(activationFunctionArray obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~activationFunctionArray() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          fannfloatPINVOKE.delete_activationFunctionArray(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public activationFunctionArray(int nelements) : this(fannfloatPINVOKE.new_activationFunctionArray(nelements), true) {
  }

  public activation_function_enum getitem(int index) {
    activation_function_enum ret = (activation_function_enum)fannfloatPINVOKE.activationFunctionArray_getitem(swigCPtr, index);
    return ret;
  }

  public void setitem(int index, activation_function_enum value) {
    fannfloatPINVOKE.activationFunctionArray_setitem(swigCPtr, index, (int)value);
  }

  public SWIGTYPE_p_FANN__activation_function_enum cast() {
    global::System.IntPtr cPtr = fannfloatPINVOKE.activationFunctionArray_cast(swigCPtr);
    SWIGTYPE_p_FANN__activation_function_enum ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_FANN__activation_function_enum(cPtr, false);
    return ret;
  }

  public static activationFunctionArray frompointer(SWIGTYPE_p_FANN__activation_function_enum t) {
    global::System.IntPtr cPtr = fannfloatPINVOKE.activationFunctionArray_frompointer(SWIGTYPE_p_FANN__activation_function_enum.getCPtr(t));
    activationFunctionArray ret = (cPtr == global::System.IntPtr.Zero) ? null : new activationFunctionArray(cPtr, false);
    return ret;
  }

}

}
