//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace FannWrapper {

public enum ActivationFunction {
  LINEAR = 0,
  THRESHOLD,
  THRESHOLD_SYMMETRIC,
  SIGMOID,
  SIGMOID_STEPWISE,
  SIGMOID_SYMMETRIC,
  SIGMOID_SYMMETRIC_STEPWISE,
  GAUSSIAN,
  GAUSSIAN_SYMMETRIC,
  GAUSSIAN_STEPWISE,
  ELLIOT,
  ELLIOT_SYMMETRIC,
  LINEAR_PIECE,
  LINEAR_PIECE_SYMMETRIC,
  SIN_SYMMETRIC,
  COS_SYMMETRIC
}

}
