//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace FannWrapper {

public enum fann_activationfunc_enum {
  FANN_LINEAR = 0,
  FANN_THRESHOLD,
  FANN_THRESHOLD_SYMMETRIC,
  FANN_SIGMOID,
  FANN_SIGMOID_STEPWISE,
  FANN_SIGMOID_SYMMETRIC,
  FANN_SIGMOID_SYMMETRIC_STEPWISE,
  FANN_GAUSSIAN,
  FANN_GAUSSIAN_SYMMETRIC,
  FANN_GAUSSIAN_STEPWISE,
  FANN_ELLIOT,
  FANN_ELLIOT_SYMMETRIC,
  FANN_LINEAR_PIECE,
  FANN_LINEAR_PIECE_SYMMETRIC,
  FANN_SIN_SYMMETRIC,
  FANN_COS_SYMMETRIC,
  FANN_SIN,
  FANN_COS
}

}
