//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace FannWrapper {

public enum fann_stopfunc_enum {
  FANN_STOPFUNC_MSE = 0,
  FANN_STOPFUNC_BIT
}

}
