//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace FannWrapper {

public enum training_algorithm_enum {
  TRAIN_INCREMENTAL = fann_train_enum.FANN_TRAIN_INCREMENTAL,
  TRAIN_BATCH,
  TRAIN_RPROP,
  TRAIN_QUICKPROP,
  TRAIN_SARPROP
}

}
