//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

using FannWrapper;
namespace FannWrapperDouble {

public class activationFunctionEnumArray : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal activationFunctionEnumArray(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(activationFunctionEnumArray obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~activationFunctionEnumArray() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SwigFannDoublePINVOKE.delete_activationFunctionEnumArray(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public activationFunctionEnumArray(int nelements) : this(SwigFannDoublePINVOKE.new_activationFunctionEnumArray(nelements), true) {
  }

  public activation_function_enum getitem(int index) {
    activation_function_enum ret = (activation_function_enum)SwigFannDoublePINVOKE.activationFunctionEnumArray_getitem(swigCPtr, index);
    return ret;
  }

  public void setitem(int index, activation_function_enum value) {
    SwigFannDoublePINVOKE.activationFunctionEnumArray_setitem(swigCPtr, index, (int)value);
  }

  public SWIGTYPE_p_FANN__activation_function_enum cast() {
    global::System.IntPtr cPtr = SwigFannDoublePINVOKE.activationFunctionEnumArray_cast(swigCPtr);
    SWIGTYPE_p_FANN__activation_function_enum ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_FANN__activation_function_enum(cPtr, false);
    return ret;
  }

  public static activationFunctionEnumArray frompointer(SWIGTYPE_p_FANN__activation_function_enum t) {
    global::System.IntPtr cPtr = SwigFannDoublePINVOKE.activationFunctionEnumArray_frompointer(SWIGTYPE_p_FANN__activation_function_enum.getCPtr(t));
    activationFunctionEnumArray ret = (cPtr == global::System.IntPtr.Zero) ? null : new activationFunctionEnumArray(cPtr, false);
    return ret;
  }

}

}
