//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------
/*
 * Title: FANN C# Connection float
 */
using FannWrapperFloat;
namespace FANNCSharp
{
    /* Class: ConnectionFloat

        Describes a connection between two neurons and its weight

        FromNeuron - Unique number used to identify source neuron
        ToNeuron - Unique number used to identify destination neuron
        Weight - The numerical value of the weight

        See Also:
            <NeuralNetFloat.Connections>

       This structure appears in FANN >= 2.1.0
    */
    public class ConnectionFloat : global::System.IDisposable
    {
        private global::System.Runtime.InteropServices.HandleRef swigCPtr;
        protected bool swigCMemOwn;
        
        public ConnectionFloat()
        {
            FromNeuron = 0;
            ToNeuron = 0;
            Weight = 0F;
        }
        /* Constructor: ConnectionFloat

            Creates a connection with the specified parameters

            Parameters:
                fromNeuron - Unique number used to identify source neuron
                toNeuron - Unique number used to identify destination neuron
                weight - The numerical value of the weight

            Example:
              >ConnectionFloat connection(2, 7, 0.5);
         */
        public ConnectionFloat(uint fromNeuron, uint toNeuron, float weight)
        {
            FromNeuron = fromNeuron;
            ToNeuron = toNeuron;
            Weight = weight;
        }
        internal ConnectionFloat(global::System.IntPtr cPtr, bool cMemoryOwn)
        {
            swigCMemOwn = cMemoryOwn;
            swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
        }

        internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ConnectionFloat obj)
        {
            return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
        }

        ~ConnectionFloat()
        {
            Dispose();
        }
        /* Method: Dispose
        
            Destructs the connection. Must be called manually.
        */
        public virtual void Dispose()
        {
            lock (this)
            {
                if (swigCPtr.Handle != global::System.IntPtr.Zero)
                {
                    if (swigCMemOwn)
                    {
                        swigCMemOwn = false;
                        fannfloatPINVOKE.delete_ConnectionFloat(swigCPtr);
                    }
                    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
                }
                global::System.GC.SuppressFinalize(this);
            }
        }
        /* Property: FromNeuron
           Unique number used to identify source neuron
         */
        public uint FromNeuron
        {
            set
            {
                fannfloatPINVOKE.ConnectionFloat_FromNeuron_set(swigCPtr, value);
            }
            get
            {
                uint ret = fannfloatPINVOKE.ConnectionFloat_FromNeuron_get(swigCPtr);
                return ret;
            }
        }
        /* Property: ToNeuron
           Unique number used to identify destination neuron
         */
        public uint ToNeuron
        {
            set
            {
                fannfloatPINVOKE.ConnectionFloat_ToNeuron_set(swigCPtr, value);
            }
            get
            {
                uint ret = fannfloatPINVOKE.ConnectionFloat_ToNeuron_get(swigCPtr);
                return ret;
            }
        }
        /* Property: Weight
           The numerical value of the weight
         */
        public float Weight
        {
            set
            {
                fannfloatPINVOKE.ConnectionFloat_Weight_set(swigCPtr, value);
            }
            get
            {
                float ret = fannfloatPINVOKE.ConnectionFloat_Weight_get(swigCPtr);
                return ret;
            }
        }

    }

}
