//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------
/*
 * Title: FANN C# Connection double
 */
using FannWrapperDouble;
namespace FANNCSharp
{
    /* Class: ConnectionDouble

        Describes a connection between two neurons and its weight

        FromNeuron - Unique number used to identify source neuron
        ToNeuron - Unique number used to identify destination neuron
        Weight - The numerical value of the weight

        See Also:
            <NeuralNetDouble.Connections>

       This structure appears in FANN >= 2.1.0
    */
    public class ConnectionDouble : global::System.IDisposable
    {
        private global::System.Runtime.InteropServices.HandleRef swigCPtr;
        protected bool swigCMemOwn;

        internal ConnectionDouble()
        {
            FromNeuron = 0;
            ToNeuron = 0;
            Weight = 0;
        }
        /* Constructor: ConnectionDouble

            Creates a connection with the specified parameters

            Parameters:
                fromNeuron - Unique number used to identify source neuron
                toNeuron - Unique number used to identify destination neuron
                weight - The numerical value of the weight

            Example:
              >ConnectionDouble connection(2, 7, 0.5);
         */
        public ConnectionDouble(uint fromNeuron, uint toNeuron, double weight)
        {
            FromNeuron = fromNeuron;
            ToNeuron = toNeuron;
            Weight = weight;
        }
        internal ConnectionDouble(global::System.IntPtr cPtr, bool cMemoryOwn)
        {
            swigCMemOwn = cMemoryOwn;
            swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
        }

        internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ConnectionDouble obj)
        {
            return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
        }

        ~ConnectionDouble()
        {
            Dispose();
        }
        /* Method: Dispose
        
            Destructs the connection. Must be called manually.
        */
        public virtual void Dispose()
        {
            lock (this)
            {
                if (swigCPtr.Handle != global::System.IntPtr.Zero)
                {
                    if (swigCMemOwn)
                    {
                        swigCMemOwn = false;
                        fanndoublePINVOKE.delete_ConnectionDouble(swigCPtr);
                    }
                    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
                }
                global::System.GC.SuppressFinalize(this);
            }
        }
        /* Property: FromNeuron
           Unique number used to identify source neuron
         */
        public uint FromNeuron
        {
            set
            {
                fanndoublePINVOKE.ConnectionDouble_FromNeuron_set(swigCPtr, value);
            }
            get
            {
                uint ret = fanndoublePINVOKE.ConnectionDouble_FromNeuron_get(swigCPtr);
                return ret;
            }
        }
        /* Property: ToNeuron
           Unique number used to identify destination neuron
         */
        public uint ToNeuron
        {
            set
            {
                fanndoublePINVOKE.ConnectionDouble_ToNeuron_set(swigCPtr, value);
            }
            get
            {
                uint ret = fanndoublePINVOKE.ConnectionDouble_ToNeuron_get(swigCPtr);
                return ret;
            }
        }
        /* Property: Weight
           The numerical value of the weight
         */
        public double Weight
        {
            set
            {
                fanndoublePINVOKE.ConnectionDouble_Weight_set(swigCPtr, value);
            }
            get
            {
                double ret = fanndoublePINVOKE.ConnectionDouble_Weight_get(swigCPtr);
                return ret;
            }
        }
    }

}
