//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------
/*
 * Title: FANN C# DoubleArrayAccessor
 */
using FannWrapperDouble;
namespace FANNCSharp
{
    /* Class: DoubleArrayAccessor
       
       Provides fast access to an array of array of doubles
    */
    public class DoubleArrayAccessor : global::System.IDisposable
    {
        private global::System.Runtime.InteropServices.HandleRef swigCPtr;
        protected bool swigCMemOwn;

        internal DoubleArrayAccessor(global::System.IntPtr cPtr, bool cMemoryOwn)
        {
            swigCMemOwn = cMemoryOwn;
            swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
        }

        internal static global::System.Runtime.InteropServices.HandleRef getCPtr(DoubleArrayAccessor obj)
        {
            return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
        }

        ~DoubleArrayAccessor()
        {
            Dispose();
        }
        /* Method: Dispose
        
            Destructs the accessor. Must be called manually.
        */
        public virtual void Dispose()
        {
            lock (this)
            {
                if (swigCPtr.Handle != global::System.IntPtr.Zero)
                {
                    if (swigCMemOwn)
                    {
                        swigCMemOwn = false;
                        fanndoublePINVOKE.delete_DoubleArrayAccessor(swigCPtr);
                    }
                    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
                }
                global::System.GC.SuppressFinalize(this);
            }
        }
        /* Method: Get
           Parameters:
                      index - The index of the array to return
   
            Return:
                 A <DoubleAccessor> that provides fast access to an array
                 of doubles
        */
        public DoubleAccessor Get(int index)
        {
            global::System.IntPtr cPtr = fanndoublePINVOKE.DoubleArrayAccessor_Get__SWIG_0(swigCPtr, index);
            DoubleAccessor ret = (cPtr == global::System.IntPtr.Zero) ? null : new DoubleAccessor(cPtr, false);
            return ret;
        }
        /* Method: Get
           Parameters:
                      x - The index of the array to access
                      y - The index in array x to return
   
            Return:
                 A double at position x,y in the array
        */
        public double Get(int x, int y)
        {
            double ret = fanndoublePINVOKE.DoubleArrayAccessor_Get__SWIG_1(swigCPtr, x, y);
            return ret;
        }

        internal static DoubleArrayAccessor FromPointer(SWIGTYPE_p_p_double t)
        {
            global::System.IntPtr cPtr = fanndoublePINVOKE.DoubleArrayAccessor_FromPointer(SWIGTYPE_p_p_double.getCPtr(t));
            DoubleArrayAccessor ret = (cPtr == global::System.IntPtr.Zero) ? null : new DoubleArrayAccessor(cPtr, false);
            return ret;
        }
    }
}
