//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------
/*
 * Title: FANN C# DataAccessor double
 */
using FannWrapperDouble;
using System.Collections.Generic;
using FANNCSharp;
namespace FANNCSharp.Double
{
    /* Class: DataAccessor
       
       Provides fast access to an array of doubles
    */
    public class DataAccessor : IReadOnlyList<double>, global::System.IDisposable
    {
        private global::System.Runtime.InteropServices.HandleRef swigCPtr;
        protected bool swigCMemOwn;

        internal DataAccessor(global::System.IntPtr cPtr, bool cMemoryOwn)
        {
            swigCMemOwn = cMemoryOwn;
            swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
        }

        internal static global::System.Runtime.InteropServices.HandleRef getCPtr(DataAccessor obj)
        {
            return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
        }
        internal void SetLength(int length)
        {
            ArrayCount = length;
        }

        ~DataAccessor()
        {
            Dispose();
        }
        /* Method: Dispose
        
            Destructs the accessor. Must be called manually.
        */
        public virtual void Dispose()
        {
            lock (this)
            {
                if (swigCPtr.Handle != global::System.IntPtr.Zero)
                {
                    if (swigCMemOwn)
                    {
                        swigCMemOwn = false;
                        fanndoublePINVOKE.delete_DoubleAccessor(swigCPtr);
                    }
                    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
                }
                global::System.GC.SuppressFinalize(this);
            }
        }
        /* Property: Item
           Parameters:
                      index - The index of the element to return
   
            Return:
                 A double at index
        */
        public double this[int index]
        {
            get
            {
                double ret = fanndoublePINVOKE.DoubleAccessor_Get(swigCPtr, index);
                return ret;
            }
        }

        /*  Method: GetEnumerator
            Returns an enumerator that can enumerate over the collection of ints
         */
        public IEnumerator<double> GetEnumerator()
        {
            return (IEnumerator<double>)new AccessorEnumerator<double>(this);
        }
        System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator()
        {
            return new AccessorEnumerator<double>(this);
        }

        internal static DataAccessor FromPointer(SWIGTYPE_p_double t)
        {
            global::System.IntPtr cPtr = fanndoublePINVOKE.DoubleAccessor_FromPointer(SWIGTYPE_p_double.getCPtr(t));
            DataAccessor ret = (cPtr == global::System.IntPtr.Zero) ? null : new DataAccessor(cPtr, false);
            return ret;
        }

        /*  Property: Count
            The number of doubles this object holds 
         */
        public int Count
        {
            get
            {
                return ArrayCount;
            }
        }
        internal int ArrayCount { get; set; }
    }
}
