//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------
/*
 * Title: FANN C# FloatArrayAccessor
 */
using FannWrapperFloat;
namespace FANNCSharp
{
    /* Class: FloatArrayAccessor
       
       Provides fast access to an array of array of floats
    */
    public class FloatArrayAccessor : global::System.IDisposable
    {
        private global::System.Runtime.InteropServices.HandleRef swigCPtr;
        protected bool swigCMemOwn;

        internal FloatArrayAccessor(global::System.IntPtr cPtr, bool cMemoryOwn)
        {
            swigCMemOwn = cMemoryOwn;
            swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
        }

        internal static global::System.Runtime.InteropServices.HandleRef getCPtr(FloatArrayAccessor obj)
        {
            return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
        }

        ~FloatArrayAccessor()
        {
            Dispose();
        }
        /* Method: Dispose
        
            Destructs the accessor. Must be called manually.
        */
        public virtual void Dispose()
        {
            lock (this)
            {
                if (swigCPtr.Handle != global::System.IntPtr.Zero)
                {
                    if (swigCMemOwn)
                    {
                        swigCMemOwn = false;
                        fannfloatPINVOKE.delete_FloatArrayAccessor(swigCPtr);
                    }
                    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
                }
                global::System.GC.SuppressFinalize(this);
            }
        }
        /* Method: Get
           Parameters:
                      index - The index of the array to return
   
            Return:
                 A <FloatAccessor> that provides fast access to an array
                 of floats
        */
        public FloatAccessor Get(int index)
        {
            global::System.IntPtr cPtr = fannfloatPINVOKE.FloatArrayAccessor_Get__SWIG_0(swigCPtr, index);
            FloatAccessor ret = (cPtr == global::System.IntPtr.Zero) ? null : new FloatAccessor(cPtr, false);
            return ret;
        }
        /* Method: Get
           Parameters:
                      x - The index of the array to access
                      y - The index in array x to return
   
            Return:
                 A float at position x,y in the array
        */
        public float Get(int x, int y)
        {
            float ret = fannfloatPINVOKE.FloatArrayAccessor_Get__SWIG_1(swigCPtr, x, y);
            return ret;
        }

        internal static FloatArrayAccessor FromPointer(SWIGTYPE_p_p_float t)
        {
            global::System.IntPtr cPtr = fannfloatPINVOKE.FloatArrayAccessor_FromPointer(SWIGTYPE_p_p_float.getCPtr(t));
            FloatArrayAccessor ret = (cPtr == global::System.IntPtr.Zero) ? null : new FloatArrayAccessor(cPtr, false);
            return ret;
        }
    }
}
